### ISSUE TITLE
Get Invoice PDF from Odoo 16.0

### ISSUE THREAD

**Issue by DEV01Divoli** [LordVeovis/xmlrpc#26]
Is this library smart enough to get the invoice pdf back on query as stream or so ? I am not able to find any source for this. If anybody have an idea on this, that would be nice.

**Comment by LordVeovis** [comment]
Hi @DEV01Divoli ,

I don't know Odoo. But you can't mix XML-RPC and stream. You send a xml request, then you receive an xml response.
Having a PDF as stream seems useless to me as it means the xml response has been fully received, so does the PDF somewhere in RAM.
